// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sthwxyofzgqkxiniwkrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0aHd4eW9memdxa3hpbml3a3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MDk1MDgsImV4cCI6MjA3MDI4NTUwOH0.OKca9z_MTYQmLESVZFdQaDT8t39yVERW0RxfD3Kulk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});